---
 name: install gitolite
 package: name=gitolite state=present

- name: make git user
  user: name={{gitolite_user}} home={{ git_repo_root_path }}

- name: install gitconfig
  template: src=gitconfig.j2 dest={{ git_repo_root_path }}/.gitconfig owner={{gitolite_user}} group={{gitolite_group}} mode=0600

- name: install gitolite.rc
  template: src=gitolite.rc.j2 dest={{ git_repo_root_path }}/.gitolite.rc owner={{gitolite_user}} group={{gitolite_group}} mode=0600

- name: generate gitolite-admin ssh key
  become: true
  become_user: '{{ gitolite_user }}'
  command: ssh-keygen -b 4096 -N "" -f {{ git_repo_root_path }}/id_rsa creates="{{ git_repo_root_path }}/id_rsa"
  register: adminkey

- name: install gitolite
  become: true
  become_user: '{{ gitolite_user }}'
  command: gitolite setup -pk {{ git_repo_root_path }}/id_rsa.pub
  when: adminkey.changed

- name: clone gitolite-admin
  become: true
  become_user: '{{ gitolite_user }}'
  git:
    repo: '{{ git_repo_root_path }}/repositories/gitolite-admin.git'
    dest: '{{ git_repo_root_path }}/gitolite-admin'
  tags: ["archusers"]

- name: git reset to remove any previous failed attempts
  become: true
  become_user: '{{ gitolite_user }}'
  command: git reset --hard
  args:
      chdir: '{{ git_repo_root_path }}/gitolite-admin'
  tags: ["archusers"]

- name: install gitolite.conf
  template: src=gitolite.conf.j2 dest={{ git_repo_root_path }}/gitolite-admin/conf/gitolite.conf owner={{ gitolite_user }} group={{ gitolite_group }} mode=0644
  register: config
  tags: ["archusers"]

- name: install gitolite access
  copy:
      src: '../pubkeys/{{ item.ssh_key }}.pub'
      dest: '{{ git_repo_root_path }}/gitolite-admin/keydir/{{ item.ssh_key }}.pub'
      mode: 0640
      owner: '{{ gitolite_user }}'
      group: '{{ gitolite_group }}'
  with_items: 
     - "{{ arch_users }}"
  when: item.ssh_key is defined
  register: keys
  tags: ["archusers"]

- name: get list of current ssh keys in gitolite
  find: paths="{{ git_repo_root_path }}/gitolite-admin/keydir" file_type="files"
  register: all_users
  tags: ["archusers"]

- name: remove ssh keys of removed users
  file: path="{{git_repo_root_path}}/gitolite-admin/keydir/{{item}}.pub" state=absent
  when: item not in "{{ arch_users }}"
  with_items: "{{ all_users.files | map(attribute='path') | map('basename') | map('splitext') | map('first') | list }}"
  tags: ["archusers"]

- name: add all files
  become: true
  become_user: '{{ gitolite_user }}'
  command: git add . 
  args:
      chdir: '{{ git_repo_root_path }}/gitolite-admin'
  when: config.changed or keys.changed
  tags: ["archusers"]

- name: commit gitolite config
  become: true
  become_user: '{{ gitolite_user }}'
  command: git commit -am "Updated gitolite-admin by Ansible"
  args:
      chdir: '{{ git_repo_root_path }}/gitolite-admin'
  when: config.changed or keys.changed
  tags: ["archusers"]

- name: push config
  become: true
  become_user: '{{ gitolite_user }}'
  command: gitolite push
  args:
      chdir: '{{ git_repo_root_path }}/gitolite-admin'
  when: config.changed or keys.changed
  tags: ["archusers"]
