---
- name: install cgit
  package: name=cgit state=present

- name: make cgit user
  user: name={{cgit_user}} home={{ cgit_path }}

- name: append groups to www-data 
  user:
    name: www-data
    groups: "{{ item }}" 
    append: yes
  with_items:
      - cgit
      - git
      - "{{cgit_user}}"
      - "{{gitolite_user}}"

- name: install cgit files
  copy: src=files/git.archlinux.org/ dest={{cgit_path}}/ owner=root group=root mode=0644

- name: install cgitrc
  template: src=cgitrc.j2 dest=/etc/cgitrc owner=root group=root mode=0644

- name: make nginx log dir
  file: path=/var/log/nginx/{{ cgit_domain }} state=directory owner=root group=root mode=755

- name: install letsencrypt cert
  command: certbot certonly --rsa-key-size 4096 --renew-by-default --webroot -w /var/www/challenges -d {{ cgit_domain }} creates=/etc/letsencrypt/live/{{cgit_domain}}

- name: install nginx file
  template: src=nginx.d.conf.j2 dest=/etc/nginx/nginx.d/{{cgit_domain}}.conf owner=root group=root mode=0644
  notify: 
    - restart nginx
